# Generated by Django 5.0.2 on 2024-02-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
