# Generated by Django 5.0.2 on 2024-02-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productmodel_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('lessons', models.ManyToManyField(to='product.lessonmodel')),
                ('products', models.ManyToManyField(to='product.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='students',
            field=models.ManyToManyField(to='product.studentmodel'),
        ),
    ]
