# Generated by Django 5.0.2 on 2024-02-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_studentmodel_groupmodel_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='lessons',
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='lessons',
            field=models.ManyToManyField(to='product.lessonmodel'),
        ),
    ]
