# Generated by Django 5.0.2 on 2024-02-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_studentmodel_lessons_groupmodel_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='students',
            field=models.ManyToManyField(blank=True, to='product.studentmodel'),
        ),
    ]
