# Generated by Django 5.0.2 on 2024-02-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_groupmodel_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='students',
            field=models.ManyToManyField(blank=True, to='product.studentmodel'),
        ),
    ]
